NASA = read.table("/Users/yynpy/Desktop/resources/coursera/data visualization/Programming Assignment 1 Data New/ExcelFormattedGISTEMPDataCSV.csv", sep = ",", header = T)
NASA = NASA[-1,]
NASA = NASA[-135,]
Year = NASA$Year
DJF = as.numeric(as.character(NASA$DJF))
MAM = as.numeric(as.character(NASA$MAM))
JJA = as.numeric(as.character(NASA$JJA))
SON = as.numeric(as.character(NASA$SON))
D.N = as.numeric(as.character(NASA$D.N))
plot(Year,DJF,type = 'l', ylab = 'Tempreture',col = 'purple')
lines(Year,MAM,col = 'green')
lines(Year,JJA,col = 'cyan')
lines(Year,SON,col = 'Orange')
#lines(Year,D.N,col = 'grey')
abline(h=0,lwd=0.2,col="grey")
abline(h=10,lwd=0.2,col="grey")
abline(h=20,lwd=0.2,col="grey")
abline(h=30,lwd=0.2,col="grey")
abline(h=40,lwd=0.2,col="grey")
abline(h=50,lwd=0.2,col="grey")
abline(h=-10,lwd=0.2,col="grey")
abline(h=-20,lwd=0.2,col="grey")
abline(h=-30,lwd=0.2,col="grey")
abline(h=-40,lwd=0.2,col="grey")
abline(h=-50,lwd=0.2,col="grey")
abline(h=-60,lwd=0.2,col="grey")
legend("top",c("Winter","Spring","Summer","Autumn"),col=c('purple','green','blue','Orange'),lty=c(1,1,1,1))
